for unified

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -144,10 +144,10 @@ if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking for Project Treble...";
   if [ "$(file_getprop /system/build.prop ro.treble.enabled)" == "true" ]; then
     ui_print "Treble Status: Supported";
-    #dtb=/tmp/anykernel/dtb-treble;
+    dtb=$home/treble;
   else
     ui_print "Treble Status: Not supported";
-    #dtb=/tmp/anykernel/dtb-nontreble;
+    dtb=$home/nontreble;
   fi;
 fi;
 
@@ -208,6 +208,10 @@ ui_print " ";
 ui_print "Installing...";
 core=$($bb grep -oE 'ak.*core.sh' anykernel.sh);
 test -f tools/$core || $bb ln -s $home/tools/ak*-core.sh $home/tools/$core;
+cat $home/kernel/Image.gz $dtb/*.dtb > $home/Image.gz-dtb;
+if [ $? != "0" ]; then
+  abort "DTB append failed. Aborting...";
+fi;
 PATH="$home/bin:$PATH" home=$home $bb ash anykernel.sh $2;
 if [ $? != 0 ]; then
   abort;
